### ISSUE TITLE
Error MSB4036

### ISSUE THREAD

**Issue by muelli01** [Fournux/vkbasalt-configurator#2]
I cloned this project on a Linux Mint 21.3 and got this when trying to run it with .NET 7.0:

vkbasalt-configurator/vkbasalt-configurator.csproj(25,5): error MSB4036: The "JsonPeek" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "/usr/lib/dotnet/sdk/7.0.115" directory.

The build failed. Fix the build errors and run again.

Any advice?

**Comment by EmilHeilbo** [comment]
You'll need to run `dotnet restore` before `dotnet run`; you'll likely need to install `blueprint-compiler` via your system's package manager as well, unless you already have that installed :slightly_smiling_face:
